### ISSUE TITLE
Compilation warning after upgrading to webpack 5.22.0

### ISSUE THREAD

**Issue by rainerborene** [omrilotan/paraphrase#15]
```
WARNING in ./node_modules/paraphrase/index.js 1:292-296
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/home/devbox/Projects/example/node_modules/webpack/lib/dependencies/ContextDependency.js:82:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/devbox/Projects/example/node_modules/webpack/lib/Compilation.js:2451:24)
    at /home/devbox/Projects/example/node_modules/webpack/lib/Compilation.js:2083:10
    at eval (eval at create (/home/devbox/Projects/example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
    at /home/devbox/Projects/example/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:332:11
    at /home/devbox/Projects/example/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/devbox/Projects/example/node_modules/neo-async/async.js:2850:39)
    at /home/devbox/Projects/example/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:311:18
    at /home/devbox/Projects/example/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/devbox/Projects/example/node_modules/neo-async/async.js:2850:39)

webpack 5.22.0 compiled with 1 warning in 45182 ms
```

**Comment by omrilotan** [comment]
Interesting. Are you bundling for browser or nodejs? This may be a conflict with Parcel bundler.
Would you be interested in trying a release candidate version w/o a bundled dist file, only source (so your bunlder, webpack, makes all the decisions)?

**Comment by rainerborene** [comment]
@omrilotan Browser. Sure, that would be great.

**Comment by omrilotan** [comment]
@rainerborene please try
```
npm i paraphrase@remove-compiled-version
```

**Comment by rainerborene** [comment]
@omrilotan Just for posterity I had to specify it using the `resolutions` config on `package.json` because it is being used as a dependency of `@fiverr/i18n` project:
```json
"resolutions": {
  "paraphrase": "2.0.0-rc.1-42d32f3"
}
```
Anyway, it works now!
